### ISSUE TITLE
tabs and spaces

### ISSUE THREAD

**Issue by szabgab** [CPAN-Security/Net-CVE#3]
I noticed that in `lib/Net/CVE.pm` some lines are indented with tabs, some with spaces. Is that intentional?

**Comment by Tux** [comment]
It is a mix, and I **really** don't care that it is mixed, as noted in https://github.com/Tux/Net-CVE/blob/main/CONTRIBUTING.md#style and in https://tux.nl/style.html#indent_code

**Comment by szabgab** [comment]
Oh. I looked at that page and apparently missed that line.
