### ISSUE TITLE
min version is currently 5.18

### ISSUE THREAD

**Issue by szabgab** [CPAN-Security/Net-CVE#7]
I configured the CI to run on older versions of Perl as well.
It failed on 5.14.2, 5.14.4, 5.16.3
The first version where it worked was 5.18.4 (I did not try on earlier 5.18.x)

In case you'd like to adjust the code or the min requirement in Makefile.PL

**Comment by Tux** [comment]
I am very curious why
```
$ perlver CVE.pm
   --------------------------------------
 | file   | explicit | syntax  | external |
 | -------------------------------------- |
 | CVE.pm | v5.14.2  | v5.10.0 | n/a      |
 | -------------------------------------- |
 | Minimum explicit version : v5.14.2     |
 | Minimum syntax version   : v5.10.0     |
 | Minimum version of perl  : v5.14.2     |
   --------------------------------------
```
If I install JSON::MaybeXS on 5.18.4 (or 5.18.0, 5.18.1, 5.18.2 or 5.18.3), `get` still fails.
Finding out why it fails will be something to dig into later.

**Comment by Tux** [comment]
BingOS proved it to be likely the requirement of IO::Socket::SSL-1.42 or up for https://
That is now a minimum in 0.004
